'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { MessageCircle,ArrowRight } from 'lucide-react';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { ReservationFields } from './reservation';
import type { Reservation } from '@/lib/group-types';
import { rememberGroup } from '@/lib/group-registry';

export function CreateGroup({initial,title}:{initial:Reservation;title:string}){
 const router=useRouter();const [open,setOpen]=useState(false),[booking,setBooking]=useState(initial),[name,setName]=useState(''),[groupTitle,setTitle]=useState(title),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const response=await fetch('/api/groups',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:groupTitle,name,reservation:booking})});const data=await response.json();if(!response.ok)throw new Error(data.error);rememberGroup(data.id);sessionStorage.setItem(`encopa-invite-${data.id}`,data.invite);router.push(`/groups/${data.id}`)}catch(e){setError(e instanceof Error?e.message:'作成できませんでした。');setBusy(false)}}
 return <><section className="mt-5 rounded-[24px] border border-[#d03e28]/15 bg-white p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-[#fdeae5] text-[#d03e28]"><MessageCircle/></span><div><h2 className="font-semibold">この会のグループをつくる</h2><p className="mt-1 text-sm text-[#6b635c]">予約内容も、待ち合わせの連絡も、ここに。</p></div></div><button className="enc-primary" onClick={()=>{setBooking(initial);setTitle(title);setError('');setOpen(true)}}>グループを作る <ArrowRight size={16}/></button></div><p className="mt-3 text-xs leading-5 text-[#6b635c]">招待リンクから参加できます。住所と実際の予約内容を確認して登録してください。</p></section><Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] overflow-y-auto bg-[#fffaf5] sm:max-w-[620px]"><DialogHeader><DialogTitle>会のグループを作成</DialogTitle><DialogDescription>招待した参加者に共有する内容を確認して作成します。予約番号は公開範囲を選べます。</DialogDescription></DialogHeader><form onSubmit={create} className="space-y-4"><label className="block text-sm">会の名前<input required maxLength={80} className="enc-input mt-1" value={groupTitle} onChange={e=>setTitle(e.target.value)}/></label><label className="block text-sm">幹事の表示名<input required maxLength={30} autoComplete="nickname" className="enc-input mt-1" value={name} onChange={e=>setName(e.target.value)}/></label><ReservationFields value={booking} onChange={setBooking}/><p className="text-xs leading-5 text-[#6b635c]">グループは90日間、参加情報は30日間有効です。幹事の操作権限はこのブラウザに保存されます。</p>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<button disabled={busy} className="enc-primary w-full">{busy?'作成中…':'グループを作成する'}</button></form></DialogContent></Dialog></>
}
