'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowLeft,CircleHelp,Copy,MessageCircle,PenLine,RefreshCw,Send,Users,Settings2,UserCheck,UserX } from 'lucide-react';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { EMPTY_ALLERGY,RSVP_LABELS,RSVP_ORDER,type AllergyProfile,type GroupView,type Reservation,type Rsvp } from '@/lib/group-types';
import { MESSAGE_KINDS,MESSAGE_KIND_LABELS,composeMessage,type MessageKind } from '@/lib/message-draft';
import { AllergyPicker } from './allergy-picker';
import { ReservationCard,ReservationFields } from './reservation';
import { forgetGroup,rememberGroup } from '@/lib/group-registry';
export function GroupRoom({id}:{id:string}){
 const router=useRouter();
 const [data,setData]=useState<GroupView|null>(null),[loading,setLoading]=useState(true),[join,setJoin]=useState(false),[invite,setInvite]=useState(''),[name,setName]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[text,setText]=useState(''),[profileOpen,setProfileOpen]=useState(false),[profile,setProfile]=useState<AllergyProfile>(EMPTY_ALLERGY),[affiliation,setAffiliation]=useState(''),[editOpen,setEditOpen]=useState(false),[draft,setDraft]=useState<Reservation|null>(null),[inviteOpen,setInviteOpen]=useState(false),[inviteLink,setInviteLink]=useState(''),[destructive,setDestructive]=useState<'leave'|'delete'|null>(null),[draftOpen,setDraftOpen]=useState(false),[draftKind,setDraftKind]=useState<MessageKind>('announce'),[messageDraft,setMessageDraft]=useState('');
 const requestKey=useRef<string|null>(null);const version=useRef(0);const pending=useRef(false);
 const refresh=useCallback(async()=>{const r=await fetch(`/api/groups/${id}`,{cache:'no-store'});const body=await r.json();if(r.status===401){setJoin(true);setData(null);return}if(!r.ok)throw new Error(body.error);setData(body);rememberGroup(id);setJoin(false)},[id]);
 useEffect(()=>{let active=true;const fragment=new URLSearchParams(window.location.hash.slice(1)).get('invite')||'';
 // The invite stays in memory, not the URL or referrer, after loading.
 // Hydrate the URL fragment once; it is unavailable during server rendering.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 if(fragment){setInvite(fragment);history.replaceState(null,'',window.location.pathname)}
 const saved=sessionStorage.getItem(`encopa-invite-${id}`);if(saved){setInviteLink(`${location.origin}/groups/${id}#invite=${encodeURIComponent(saved)}`);sessionStorage.removeItem(`encopa-invite-${id}`)}
 const run=()=>refresh().catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});void run();const tick=setInterval(()=>{if(!document.hidden&&!pending.current)void run()},15000);return()=>{active=false;clearInterval(tick)};
 },[id,refresh]);
 async function action(body:Record<string,unknown>){const r=await fetch(`/api/groups/${id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const value=await r.json();if(!r.ok)throw new Error(value.error);return value}
 async function perform(fn:()=>Promise<void>){if(pending.current)return;pending.current=true;setBusy(true);setError('');setNotice('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'操作できませんでした。')}finally{pending.current=false;setBusy(false)}}
 async function joinGroup(e:React.FormEvent){e.preventDefault();await perform(async()=>{await action({action:'join',invite,name});setInvite('');await refresh()})}
 async function send(e:React.FormEvent){e.preventDefault();if(!text.trim())return;await perform(async()=>{requestKey.current??=crypto.randomUUID();await action({action:'message',text,requestKey:requestKey.current});setText('');requestKey.current=null;await refresh()})}
 async function copyInvite(){await perform(async()=>{let link=inviteLink;if(!link){const value=await action({action:'invite'});link=`${location.origin}/groups/${id}#invite=${encodeURIComponent(value.invite)}`;setInviteLink(link)}try{await navigator.clipboard.writeText(link);setNotice('招待リンクをコピーしました。参加してほしい人にだけ共有してください。')}catch{setNotice('下のリンクを選択してコピーしてください。')}setInviteOpen(true)})}
 function openDraft(kind:MessageKind){
  if(!data)return;
  setDraftKind(kind);
  setMessageDraft(composeMessage(kind,{title:data.title,reservation:data.reservation,attending:data.members.filter(m=>m.rsvp==='yes').length,pending:data.members.filter(m=>m.rsvp==='pending').length}));
  setDraftOpen(true);
 }
 async function copyDraft(){await perform(async()=>{try{await navigator.clipboard.writeText(messageDraft);setNotice('文面をコピーしました。')}catch{setNotice('コピーできませんでした。文面を選択してコピーしてください。')}})}
 const owner=data?.me.role==='owner';
 return <main className="min-h-screen bg-[#fdf6ef] text-[#211f1d]"><header className="border-b border-[#211f1d]/10 bg-[#fdf6ef]"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-4 py-4 sm:px-8"><Link href="/" className="flex items-center gap-2 font-bold tracking-wider"><ArrowLeft size={16}/> ENCOPA</Link><span className="text-xs text-[#6b635c]">会のグループ</span></div></header><div className="mx-auto max-w-6xl px-4 py-7 sm:px-8">
 {error&&<div role="alert" className="mb-4 flex flex-wrap items-center justify-between gap-2 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><span>{error}</span><button className="underline" onClick={()=>void perform(refresh)}>再読み込み</button></div>}{notice&&<p role="status" className="mb-4 rounded-xl bg-[#e6f3ec] p-4 text-sm">{notice}</p>}
 {loading?<p role="status" className="py-16 text-center">グループを開いています…</p>:join?<section className="mx-auto max-w-lg rounded-[24px] border bg-white p-6 sm:p-8"><MessageCircle className="mb-4 text-[#d03e28]" size={32}/><h1 className="text-2xl font-semibold">みんなで予定を共有しよう</h1><p className="mt-3 text-sm leading-6 text-[#6b635c]">参加すると予約内容とチャットを閲覧できます。表示名はグループ内に公開されます。</p>{invite?<form onSubmit={joinGroup} className="mt-6 space-y-4"><label className="block text-sm">表示名<input autoComplete="nickname" required maxLength={30} className="enc-input mt-2" value={name} onChange={e=>setName(e.target.value)}/></label><button disabled={busy} className="enc-primary w-full">{busy?'参加中…':'このグループに参加する'}</button></form>:<p className="mt-6 rounded-xl bg-[#fdf6ef] p-4 text-sm leading-6">幹事から受け取った招待リンクを開いてください。参加済みの場合は、参加したときと同じブラウザを使ってください。</p>}</section>:data&&<>
 <div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><p className="mb-2 text-xs font-semibold tracking-widest text-[#c03429]">OUR GATHERING</p><h1 className="break-words text-3xl font-semibold">{data.title}</h1><p className="mt-2 flex items-center gap-2 text-sm text-[#6b635c]"><Users size={16}/>メンバー{data.members.length}人 · 参加{data.members.filter(m=>m.rsvp==='yes').length}名 · {data.me.name}{owner?'（幹事）':''}</p></div><div className="flex flex-wrap gap-2"><button className="enc-secondary" disabled={busy} onClick={()=>void perform(refresh)} aria-label="再読み込み"><RefreshCw size={16}/></button>{owner&&<button className="enc-primary" disabled={busy} onClick={()=>void copyInvite()}><Copy size={16}/>招待リンク</button>}{owner&&<button className="enc-secondary" onClick={()=>openDraft('announce')}><PenLine size={16}/>お知らせ文</button>}<button className="enc-secondary" onClick={()=>{setProfile(data.me.allergy);setName(data.me.name);setAffiliation(data.me.affiliation);setProfileOpen(true)}}>自分の回答</button></div></div>
 <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,380px)_minmax(0,1fr)]"><aside className="space-y-5"><section><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">最新の予約内容</h2>{owner&&<button className="enc-secondary" onClick={()=>{setDraft(data.reservation);version.current=data.version;setEditOpen(true)}}><Settings2 size={15}/>編集</button>}</div><ReservationCard value={data.reservation}/>{owner&&<button className="enc-primary mt-3 w-full" disabled={busy} onClick={()=>void perform(async()=>{await action({action:'share',version:data.version});await refresh();setNotice('この予約内容をチャットへ共有しました。同じ版は重複投稿しません。')})}><Send size={16}/>予約内容をチャットに送る</button>}</section>
 <section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">出欠の回答</h2>
 <p className="mt-1 text-xs leading-5 text-[#6b635c]">回答は自分だけが変更できます。いつでも変えられます。</p>
 <div className="mt-3 grid grid-cols-3 gap-2">{RSVP_ORDER.map(value=>{const on=data.me.rsvp===value;return <button key={value} type="button" aria-pressed={on} disabled={busy} onClick={()=>void perform(async()=>{await action({action:'rsvp',rsvp:value});await refresh();setNotice(`出欠を「${RSVP_LABELS[value]}」で保存しました。`)})} className={`flex min-h-16 flex-col items-center justify-center gap-1 rounded-xl border text-sm font-semibold transition ${on?'border-[#d03e28] bg-[#fdeae5] text-[#c03429]':'border-[#211f1d]/12 bg-white text-[#6b635c] hover:bg-[#fdf6ef]'}`}><RsvpIcon value={value}/>{RSVP_LABELS[value]}</button>})}</div>
 <dl className="mt-4 flex items-center justify-between rounded-xl bg-[#fdf6ef] px-3 py-2.5 text-xs">{RSVP_ORDER.map(value=><div key={value} className="flex items-baseline gap-1"><dt className="whitespace-nowrap text-[#6b635c]">{RSVP_LABELS[value]}</dt><dd className="text-sm font-bold text-[#d03e28]">{data.members.filter(m=>m.rsvp===value).length}</dd></div>)}</dl>
 {owner&&data.members.filter(m=>m.rsvp==='yes').length!==data.reservation.people&&<p className="mt-3 rounded-xl bg-[#fdeae5] p-3 text-xs leading-5 text-[#8a3a22]">参加の回答は{data.members.filter(m=>m.rsvp==='yes').length}名、予約人数は{data.reservation.people}名です。締め切り後に予約内容を更新してください。</p>}
 </section>
 <section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">参加メンバー</h2><ul className="mt-3 divide-y">{data.members.map(m=><li key={m.id} className="py-3"><div className="flex items-start justify-between gap-2"><span className="min-w-0 break-words text-sm font-medium">{m.name}{m.role==='owner'?' · 幹事':''}{m.affiliation&&<span className="block text-xs font-normal text-[#6b635c]">{m.affiliation}</span>}</span><span className="flex shrink-0 items-center gap-2"><RsvpChip value={m.rsvp}/>{owner&&m.role!=='owner'&&<button className="text-xs text-[#6b635c] underline" onClick={()=>{if(window.confirm(`${m.name}さんを退出させますか？招待リンクも無効になります。`))void perform(async()=>{await action({action:'remove',memberId:m.id});setInviteLink('');await refresh()})}}>退出</button>}</span></div>{m.answeredAt>0&&<p className="mt-1 text-xs text-[#6b635c]">最終更新：<time dateTime={new Date(m.answeredAt).toISOString()}>{new Date(m.answeredAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}</time></p>}{owner&&m.allergy&&<p className="mt-1 whitespace-pre-wrap break-words text-xs leading-5 text-[#6b635c]">食物アレルギー：{m.allergy.status==='unanswered'?'未回答':m.allergy.status==='none'?'なし':`${m.allergy.items.join('、')}${m.allergy.note?` / ${m.allergy.note}`:''}`}</p>}</li>)}</ul>{owner&&<p className="mt-3 text-xs leading-5 text-[#6b635c]">アレルギーの詳細は幹事と本人にだけ表示しています。店舗への確認に使用してください。</p>}</section><p className="text-xs leading-5 text-[#6b635c]">グループの有効期限：{new Date(data.expiresAt).toLocaleDateString('ja-JP',{timeZone:'Asia/Tokyo'})}。招待リンクは7日間有効です。</p><button className="text-sm text-[#8a5a3a] underline" onClick={()=>setDestructive(owner?'delete':'leave')}>{owner?'グループを終了して削除':'このグループを退出'}</button></aside>
 <section className="min-w-0 overflow-hidden rounded-[24px] border bg-white"><div className="border-b px-5 py-4"><h2 className="flex items-center gap-2 font-semibold"><MessageCircle size={19}/>みんなのチャット</h2><p className="mt-1 text-xs text-[#6b635c]">表示中は15秒ごとに更新 · 最新100件</p></div><div className="max-h-[65vh] min-h-64 space-y-5 overflow-y-auto p-4 sm:p-5" aria-label="チャット履歴">{!data.messages.length?<div className="py-12 text-center"><MessageCircle className="mx-auto mb-3 text-[#cbbfb2]" size={32}/><p className="text-sm text-[#6b635c]">最初のひとことを送ってみましょう。</p></div>:data.messages.map(m=><article key={m.id} className={`flex ${m.authorId===data.me.id?'justify-end':'justify-start'}`}><div className="w-full max-w-[95%] sm:max-w-[88%]"><p className="mb-1 flex flex-wrap gap-x-2 text-xs text-[#6b635c]"><span className="break-words">{m.author}</span><time>{new Date(m.createdAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}</time></p>{m.kind==='reservation'&&m.reservation?<div><p className="mb-2 text-xs font-semibold text-[#d03e28]">共有時点の予約内容</p><ReservationCard value={m.reservation} compact/><p className="mt-1 text-xs text-[#6b635c]">最新情報は「最新の予約内容」を確認してください。</p></div>:<p className={`whitespace-pre-wrap break-words rounded-2xl px-4 py-3 text-sm leading-6 ${m.authorId===data.me.id?'bg-[#e6f3ec]':'bg-[#f6ece1]'}`}>{m.text}</p>}</div></article>)}</div><form onSubmit={send} className="border-t bg-[#fffaf5] p-4"><label className="sr-only" htmlFor="chat-message">メッセージ</label><textarea id="chat-message" className="enc-input min-h-24" maxLength={2000} value={text} onChange={e=>{setText(e.target.value);requestKey.current=null}} placeholder="待ち合わせや、みんなへの連絡"/><div className="mt-3 flex items-center justify-between gap-3"><span className="text-xs text-[#6b635c]">{text.length} / 2000 · グループ内に公開</span><button disabled={busy||!text.trim()} className="enc-primary"><Send size={16}/>{busy?'送信中…':'送信'}</button></div></form></section></div>
 </>}
 <Dialog open={profileOpen} onOpenChange={setProfileOpen}><DialogContent className="max-h-[90vh] overflow-y-auto bg-[#fffaf5] sm:max-w-[600px]"><DialogHeader><DialogTitle>自分の回答</DialogTitle><DialogDescription>アレルギーは本人と幹事だけが閲覧できます。未回答に戻すと登録内容を削除します。</DialogDescription></DialogHeader><form className="space-y-5" onSubmit={e=>{e.preventDefault();void perform(async()=>{await action({action:'profile',name,affiliation,allergy:profile});await refresh();setProfileOpen(false);setNotice('回答を保存しました。')})}}><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm">表示名<input className="enc-input mt-1" value={name} required maxLength={30} onChange={e=>setName(e.target.value)}/></label><label className="block text-sm">所属（任意）<input className="enc-input mt-1" value={affiliation} maxLength={40} placeholder="例：営業部" onChange={e=>setAffiliation(e.target.value)}/><span className="mt-1 block text-xs text-[#6b635c]">グループ内の全員に表示されます。</span></label></div><AllergyPicker value={profile} onChange={setProfile}/>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<button className="enc-primary w-full" disabled={busy}>回答を保存</button></form></DialogContent></Dialog>
 <Dialog open={draftOpen} onOpenChange={setDraftOpen}><DialogContent className="max-h-[90vh] overflow-y-auto bg-[#fffaf5] sm:max-w-[600px]"><DialogHeader><DialogTitle>お知らせ文をつくる</DialogTitle><DialogDescription>予約内容と出欠の集計から文面を組み立てます。送信前に自由に書き換えられます。参加者が書いた名前・所属・補足は使いません。</DialogDescription></DialogHeader>
 <div className="grid grid-cols-3 gap-2">{MESSAGE_KINDS.map(kind=><button key={kind} type="button" aria-pressed={draftKind===kind} onClick={()=>openDraft(kind)} className={`min-h-11 rounded-xl border px-2 text-sm font-semibold transition ${draftKind===kind?'border-[#d03e28] bg-[#fdeae5] text-[#c03429]':'border-[#211f1d]/12 bg-white text-[#6b635c] hover:bg-[#fdf6ef]'}`}>{MESSAGE_KIND_LABELS[kind]}</button>)}</div>
 <label className="sr-only" htmlFor="message-draft">お知らせ文</label>
 <textarea id="message-draft" className="enc-input min-h-56" maxLength={2000} value={messageDraft} onChange={e=>setMessageDraft(e.target.value)}/>
 <p className="text-xs text-[#6b635c]">{messageDraft.length} / 2000 · 投稿するとグループ内の全員に表示されます。外部への送信は行いません。</p>
 {error&&<p role="alert" className="text-sm text-red-700">{error}</p>}
 <div className="grid gap-2 sm:grid-cols-2"><button className="enc-secondary justify-center" disabled={busy||!messageDraft.trim()} onClick={()=>void copyDraft()}><Copy size={16}/>コピー</button><button className="enc-primary justify-center" disabled={busy||!messageDraft.trim()} onClick={()=>void perform(async()=>{await action({action:'message',text:messageDraft,requestKey:crypto.randomUUID()});setDraftOpen(false);await refresh();setNotice('お知らせ文をチャットに投稿しました。')})}><Send size={16}/>チャットに投稿</button></div>
 </DialogContent></Dialog>
 <Dialog open={editOpen} onOpenChange={setEditOpen}><DialogContent className="max-h-[90vh] overflow-y-auto bg-[#fffaf5] sm:max-w-[600px]"><DialogHeader><DialogTitle>予約内容を更新</DialogTitle><DialogDescription>保存すると参加者全員の予約表示が更新されます。チャットへの投稿は保存後に選べます。</DialogDescription></DialogHeader>{draft&&<form className="space-y-4" onSubmit={e=>{e.preventDefault();void perform(async()=>{await action({action:'reservation',reservation:draft,version:version.current});await refresh();setEditOpen(false);setNotice('予約内容を更新しました。必要に応じてチャットに送ってください。')})}}><ReservationFields value={draft} onChange={setDraft}/>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<button disabled={busy} className="enc-primary w-full">変更を保存</button></form>}</DialogContent></Dialog>
 <Dialog open={inviteOpen} onOpenChange={setInviteOpen}><DialogContent className="bg-[#fffaf5]"><DialogHeader><DialogTitle>参加者を招待</DialogTitle><DialogDescription>リンクを持つ人は参加できます。公開SNSなどには掲載しないでください。</DialogDescription></DialogHeader><textarea readOnly aria-label="招待リンク" className="enc-input min-h-28 break-all" value={inviteLink}/><button className="enc-primary" onClick={()=>void copyInvite()} disabled={busy}>リンクをコピー</button><button className="enc-secondary" disabled={busy} onClick={()=>void perform(async()=>{const v=await action({action:'invite'});setInviteLink(`${location.origin}/groups/${id}#invite=${encodeURIComponent(v.invite)}`);setNotice('新しい招待リンクを発行しました。以前のリンクは使えません。')})}>リンクを再発行（旧リンクを無効化）</button></DialogContent></Dialog>
 <Dialog open={!!destructive} onOpenChange={()=>setDestructive(null)}><DialogContent><DialogHeader><DialogTitle>{destructive==='delete'?'グループを削除しますか？':'グループを退出しますか？'}</DialogTitle><DialogDescription>{destructive==='delete'?'予約内容・参加者の回答・チャットを削除します。この操作は取り消せません。':'自分の回答を削除します。過去のメッセージは退会した参加者として残ります。'}</DialogDescription></DialogHeader><button className="enc-primary" disabled={busy} onClick={()=>void perform(async()=>{await action({action:destructive});forgetGroup(id);router.push('/?view=groups')})}>{destructive==='delete'?'削除する':'退出する'}</button></DialogContent></Dialog>
 </div></main>
}
const RSVP_ICONS:Record<Rsvp,React.ElementType>={yes:UserCheck,no:UserX,pending:CircleHelp};
function RsvpIcon({value}:{value:Rsvp}){const Icon=RSVP_ICONS[value];return <Icon size={18}/>}
/** 未回答を空欄にせず明示するのは、答えていないことが幹事に伝わる必要があるため。 */
function RsvpChip({value}:{value:Rsvp}){
 const tone=value==='yes'?'bg-[#e6f3ec] text-[#2f7d55]':value==='no'?'bg-[#f6ece1] text-[#6b635c]':'bg-[#fdeae5] text-[#c03429]';
 return <span className={`whitespace-nowrap rounded-full px-2.5 py-1 text-xs font-semibold ${tone}`}>{RSVP_LABELS[value]}</span>;
}
